sudo:
  false

language:
  php

php:
  - 5.5

cache:
  directories:
    - vendor

before_script:
  - composer install --dev --no-interaction --prefer-source

script:
  - vendor/bin/phpunit --configuration phpunit.xml.dist --colors

